### ISSUE TITLE
#SingleInstance Off - I can't stop my exe restarting

### ISSUE THREAD

**Issue by Gavin-Holt** [AutoHotkey/Ahk2Exe#96] opened 2023-05-03 09:49 UTC
Hi,

I have been using Hiedit.dll(4.0.04),HiEdit.ahk and Ahk2Exe.exe to write an editor application, with multiple tabs:

- https://github.com/Gavin-Holt/APEditor

In general, I am very happy with the result (no text wrapping - but that's ok). From within the application, I can open and close files with the dialogs or using drag and drop.

However, I am having trouble with SingleInstance. When talking about text editors, single instance usually means "any repeated attempts to launch the editor will simply revert to the first running instance AND open any new filename parameter in a new tab".

I use a Xtree like file manager, and would like to be able to leave the editor open and then open further files by calling the exe with a filename parameter.

After asking on the AHK forum, I have tried to detect new instances:

```
;# Setup AHK Environment
#SingleInstance Off
#NoEnv
#NoTrayIcon
#MaxMem 128
SetWorkingDir, %A_ScriptDir%
AutoTrim,Off
SetBatchLines,-1
SetControlDelay,-1
SetWinDelay,-1
ListLines, Off
DetectHiddenWindows, On
SetTitleMatchMode,2
SendMode, Input
Process,Priority,,A
CoordMode, Mouse, Relative

$MySingleInstance()

; Lower down after autoexec section
$MySingleInstance() {
    If $FirstInstance() {
        msgbox "First instance"
    } else {
        msgbox "New instance"
        ExitApp
    }
}

$FirstInstance() {
    local FirstInstancePID
    Process, Exist, %A_ScriptName%
    FirstInstancePID := ErrorLevel
    if (FirstInstancePID = DllCall("GetCurrentProcessId"))
    {
        return, true
    } else {
        return, false
    }
}
```
The approach above does not work to detect new instances of my compiled script:

- Repeated execution of APEditor.exe, from the same folder, simply restarts the editor - losing any unsaved work.
- Interestingly, if I make a copy of the compiled script in another folder, and execute that copy - the "New" instance is identified.

I have had similar results with other methods to check if an instance is already running:

- https://www.autohotkey.com/board/topic/76240-single-instance-force-compiled-scripts-only/

- https://www.autohotkey.com/boards/viewtopic.php?t=28667

My lovely customized editor is not much use, if repeated executions effectively wipe out any open tabs with data loss!

Any help welcome.

Kind Regards Gavin Holt

I am happily using old versions of AHK/AHK2EXE

- Ahk2Exe v1.0.48.05
- AutoHotkeySC.bin 25.09.2009

**Comment by TAC109** [comment] 2023-05-04 22:49
I am closing this issue because:

- This problem is not caused by Ahk2Exe.
- Even if it was, you are using an older version of Ahk2Exe distributed with AutoHotkey 1.0.48.05, which is no longer supported.
- You have also posted this problem on the forums (which is a more suitable place) and are receiving help there.

Cheers

**Closed by TAC109** 2023-05-04 22:49 UTC
